"""Migration 033 — the entity vocabulary (canonical + alias), seeded from
`entity_registry`.

No live database is used or required — everything here is a STATIC check over
the migration's own SQL text, or a pure-Python re-implementation of the
canonical-pick rule run against a synthetic fixture. That is a real limit, not
a formality: these tests cannot prove the SQL parses, that the triggers fire,
that the seed's window-function ordering actually produces what the rule
below describes, or that a fresh `schema_init.sql` install ends up equivalent
to a migrated one. `migrations/verify_schema_init.py` against a throwaway
database is what proves those, and this file cannot substitute for it.

Fixture names are deliberately generic ("AlphaBeta") — never a real project or
entity name from this corpus (`fact:1195`).
"""
import os
import re

_ROOT = os.path.join(os.path.dirname(__file__), "..")
_MIGRATIONS = os.path.join(_ROOT, "shared-memory", "migrations")
_MIGRATION_033 = os.path.join(_MIGRATIONS, "033_entity_vocabulary.sql")
_SCHEMA_INIT = os.path.join(_MIGRATIONS, "schema_init.sql")


def _read(path: str) -> str:
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def _sql() -> str:
    return _read(_MIGRATION_033)


def _code_only(text: str) -> str:
    """Strip `--` line comments. The migration's own prose (canonical-pick
    rule explanations, house-style headers) freely uses backticked SQL
    fragments containing stray single quotes — e.g. `` `metadata->'entities'` ``
    — which would otherwise be mistaken for real string literals or corrupt a
    FROM/JOIN table scan. Scanning CODE rather than the whole file is what
    keeps those checks meaningful instead of just matching this file's own
    documentation back to itself."""
    return "\n".join(
        line.split("--", 1)[0] for line in text.splitlines()
    )


# ── The file exists, in sequence, with no gap ────────────────────────────────

def test_033_exists_in_sequence_with_no_gap():
    files = sorted(f for f in os.listdir(_MIGRATIONS) if re.match(r"^\d{3}_.*\.sql$", f))
    assert "033_entity_vocabulary.sql" in files
    numbers = sorted(int(f[:3]) for f in files)
    assert numbers == list(range(min(numbers), max(numbers) + 1)), (
        "the migration chain has a gap or duplicate around 033")
    # 032 is the last migration this unit was built against — if a later
    # migration lands with a lower number than 033 the ordering assumption
    # (033 runs after everything currently in the repo) is wrong and needs a
    # human look, not a silent renumber.
    assert max(numbers) >= 33


# ── entity_normalize() — the one normalization definition ───────────────────

def test_entity_normalize_is_defined_immutable_and_lowercase_alnum_only():
    sql = _sql()
    assert "CREATE OR REPLACE FUNCTION entity_normalize(" in sql
    fn_block = sql[sql.index("CREATE OR REPLACE FUNCTION entity_normalize("):]
    fn_block = fn_block[:fn_block.index("$$;") + 3]
    assert "IMMUTABLE" in fn_block
    # The documented contract: lowercase, then strip everything not [a-z0-9].
    assert "lower(" in fn_block
    assert "[^a-z0-9]" in fn_block


# ── Both tables present, with the shape the task specifies ──────────────────

def test_both_tables_are_created():
    sql = _sql()
    assert re.search(r"CREATE TABLE IF NOT EXISTS entity_vocabulary\s*\(", sql)
    assert re.search(r"CREATE TABLE IF NOT EXISTS entity_vocab_aliases\s*\(", sql)


def test_entity_vocabulary_columns_and_constraints():
    sql = _sql()
    block = sql[sql.index("CREATE TABLE IF NOT EXISTS entity_vocabulary ("):]
    block = block[:block.index("\n);")]
    for col in ("id", "name", "normalized_key", "created_at", "registered_by"):
        assert col in block, f"entity_vocabulary missing column {col!r}"
    assert "GENERATED BY DEFAULT AS IDENTITY" in block
    assert "entity_vocabulary_normalized_key_unique UNIQUE (normalized_key)" in block


def test_entity_vocab_aliases_columns_fk_and_constraints():
    sql = _sql()
    block = sql[sql.index("CREATE TABLE IF NOT EXISTS entity_vocab_aliases ("):]
    block = block[:block.index("\n);")]
    for col in ("id", "entity_id", "alias", "normalized_alias", "created_at", "created_by"):
        assert col in block, f"entity_vocab_aliases missing column {col!r}"
    assert "REFERENCES entity_vocabulary (id) ON DELETE CASCADE" in block
    assert "entity_vocab_aliases_normalized_unique UNIQUE (normalized_alias)" in block


def test_the_cross_table_consistency_triggers_exist():
    """Eyes-only for correctness (a trigger firing correctly needs a live DB),
    but their PRESENCE and which function each calls is checkable statically."""
    sql = _sql()
    assert "CREATE TRIGGER trg_entity_vocabulary_before_write" in sql
    assert "EXECUTE FUNCTION entity_vocabulary_before_write" in sql
    assert "CREATE TRIGGER trg_entity_vocab_aliases_before_write" in sql
    assert "EXECUTE FUNCTION entity_vocab_aliases_before_write" in sql


# ── Idempotency markers ───────────────────────────────────────────────────────

def test_idempotency_markers_present():
    sql = _sql()
    assert "CREATE TABLE IF NOT EXISTS" in sql
    assert "CREATE INDEX IF NOT EXISTS" in sql
    assert "ON CONFLICT" in sql and "DO NOTHING" in sql
    assert "CREATE OR REPLACE FUNCTION" in sql
    assert "DROP TRIGGER IF EXISTS" in sql
    assert sql.strip().startswith("--")
    assert "BEGIN;" in sql and sql.rstrip().endswith("COMMIT;")


# ── entity_registry is read, never written ───────────────────────────────────

def test_entity_registry_is_never_altered_or_dropped():
    sql = _sql()
    assert not re.search(r"ALTER TABLE\s+entity_registry", sql, re.I)
    assert not re.search(r"DROP TABLE\s+(?:IF EXISTS\s+)?entity_registry", sql, re.I)
    assert not re.search(r"(?:INSERT INTO|UPDATE|DELETE FROM)\s+entity_registry\b", sql, re.I)
    assert "FROM entity_registry" in sql, "seeding must read entity_registry"


# ── The seed's shape: INSERT...SELECT, sourced only from entity_registry /
#    technical_docs — never a literal row of names ──────────────────────────

def test_seeding_is_insert_select_never_insert_values():
    seed = _code_only(_sql())
    seed = seed[seed.index("CREATE TEMP TABLE entity_vocab_seed_ranked"):]
    inserts = re.findall(r"INSERT INTO\s+entity_vocab(?:ulary|_aliases)?\s*\([^)]*\)\s*(SELECT|VALUES)",
                          seed, re.I)
    assert inserts, "expected at least one INSERT INTO entity_vocabulary/entity_vocab_aliases in the seed"
    assert all(kw.upper() == "SELECT" for kw in inserts), (
        "seeding must be INSERT ... SELECT (derived from live data), never "
        "INSERT ... VALUES (a literal list)")


def test_seed_source_is_only_entity_registry_and_technical_docs():
    seed = _code_only(_sql())
    seed = seed[seed.index("CREATE TEMP TABLE entity_vocab_seed_ranked"):]
    from_tables = set(re.findall(r"FROM\s+(\w+)", seed, re.I))
    join_tables = set(re.findall(r"JOIN\s+(\w+)", seed, re.I))
    referenced = from_tables | join_tables
    # entity_vocab_seed_ranked and entity_vocabulary/entity_vocab_aliases are
    # this migration's own temp/target tables, not external name sources.
    allowed = {"entity_registry", "technical_docs", "entity_vocab_seed_ranked",
               "entity_vocabulary", "occurrence_counts", "registry_norm"}
    assert referenced <= allowed, (
        f"seed reads from an unexpected source: {referenced - allowed} — the "
        f"vocabulary must be derived only from entity_registry/technical_docs")


_ALLOWED_SEED_STRING_LITERALS = {
    "migration_033_seed",  # the seed's own attribution, not a name
    "fact",                # metadata->>'kind' value it filters FOR
    "kind",                # JSONB key
    "entities",            # JSONB key
    "array",                # jsonb_typeof(...) = 'array' — a JSON type name
}


def test_no_string_literal_in_the_seed_looks_like_a_seeded_entity_name():
    """Scoped to CODE in the SEEDING block (comments stripped): RAISE
    EXCEPTION messages elsewhere, and this migration's own prose — which
    freely backtick-quotes SQL fragments containing stray single quotes, e.g.
    `` `metadata->'entities'` `` in the canonical-pick-rule comment — are not
    candidate entity names and would make a raw-text scan fail on the
    migration's own documentation. Every single-quoted string literal
    actually reachable by the seed's INSERTs is one of a small, known,
    structural set (JSONB keys, the seed's own attribution string) — never a
    name that could only have come from this install's own corpus.
    Portability (`fact:1195`) depends on this staying true for every future
    edit to this file, not just the first version."""
    seed = _code_only(_sql())
    seed = seed[seed.index("CREATE TEMP TABLE entity_vocab_seed_ranked"):]
    literals = re.findall(r"'((?:[^'\\]|'')*)'", seed)
    assert literals, "expected to find string literals in the seed block"
    unexpected = [lit for lit in literals if lit not in _ALLOWED_SEED_STRING_LITERALS]
    assert not unexpected, (
        f"unexpected string literal(s) in migration 033's seed — a seed must "
        f"never hardcode a name: {unexpected}")


# ── The canonical-pick rule, reference-implemented in Python ────────────────
#
# This is the one invariant that needs SEMANTICS, not just text-matching. We
# cannot run the SQL, so we re-implement the documented rule in pure Python
# against a synthetic fixture and assert it produces the outcome the rule's
# own English description promises. This does NOT prove the SQL implements
# the same rule correctly — only that the rule, AS DOCUMENTED, is internally
# coherent and deterministic. Only `verify_schema_init.py` / a live apply can
# prove the SQL itself.

def _normalize(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "", name.lower())


def _pick_canonical(rows):
    """rows: list of dicts with name, created_at (int, lower=earlier),
    occurrence_count. Mirrors migration 033's ORDER BY:
    occurrence_count DESC, created_at ASC, length(name) ASC, name ASC.
    """
    groups: dict[str, list[dict]] = {}
    for r in rows:
        groups.setdefault(_normalize(r["name"]), []).append(r)
    picks = {}
    for key, members in groups.items():
        ranked = sorted(
            members,
            key=lambda r: (-r["occurrence_count"], r["created_at"], len(r["name"]), r["name"]),
        )
        picks[key] = ranked[0]["name"]
    return picks


def test_canonical_pick_prefers_highest_occurrence_count():
    rows = [
        {"name": "AlphaBeta", "created_at": 3, "occurrence_count": 1},
        {"name": "alpha-beta", "created_at": 1, "occurrence_count": 5},
        {"name": "alpha_beta", "created_at": 2, "occurrence_count": 2},
    ]
    picks = _pick_canonical(rows)
    assert picks[_normalize("AlphaBeta")] == "alpha-beta"


def test_canonical_pick_tie_breaks_on_earliest_created_at():
    rows = [
        {"name": "GammaDelta", "created_at": 5, "occurrence_count": 3},
        {"name": "gamma-delta", "created_at": 1, "occurrence_count": 3},
    ]
    picks = _pick_canonical(rows)
    assert picks[_normalize("GammaDelta")] == "gamma-delta"


def test_canonical_pick_tie_breaks_on_shortest_name_then_lexicographic():
    # All three normalize to the same key ("epsilonzeta") — they differ only
    # by punctuation the normalizer strips, so occurrence_count and
    # created_at tie and the SHORTEST verbatim spelling must win.
    rows = [
        {"name": "Epsilon--Zeta", "created_at": 1, "occurrence_count": 0},
        {"name": "Epsilon-Zeta", "created_at": 1, "occurrence_count": 0},
        {"name": "EpsilonZeta", "created_at": 1, "occurrence_count": 0},
    ]
    assert {_normalize(r["name"]) for r in rows} == {"epsilonzeta"}, (
        "fixture bug: all three rows must land in ONE normalized group")
    picks = _pick_canonical(rows)
    assert picks["epsilonzeta"] == "EpsilonZeta"


def test_canonical_pick_is_fully_deterministic_final_tiebreak():
    # Same normalized key ("thetaiota"), same verbatim LENGTH, same count and
    # created_at — only case differs, so the final lexicographic tiebreak
    # must decide (uppercase sorts before lowercase in ASCII).
    rows = [
        {"name": "thetaiota", "created_at": 1, "occurrence_count": 0},
        {"name": "ThetaIota", "created_at": 1, "occurrence_count": 0},
    ]
    assert {_normalize(r["name"]) for r in rows} == {"thetaiota"}, (
        "fixture bug: both rows must land in ONE normalized group")
    picks = _pick_canonical(rows)
    assert picks["thetaiota"] == "ThetaIota", (
        "lexicographic tiebreak must be deterministic: 'ThetaIota' < "
        "'thetaiota' by ASCII ordering")


def test_migration_sql_orders_the_seed_by_the_documented_rule():
    """Confirms the SQL's ORDER BY clause names the same four keys, in the
    same order, that the reference implementation above uses — a textual
    check, not a semantic one, but it is what static analysis can offer here."""
    sql = _sql()
    order_by = sql[sql.index("ORDER BY oc.occurrence_count"):]
    order_by = order_by[:order_by.index(") AS rnk")]
    assert "occurrence_count DESC" in order_by
    assert "created_at ASC" in order_by
    assert "length(oc.name) ASC" in order_by
    assert "oc.name ASC" in order_by
    # DESC must come before the ASC tiebreaks in the clause, matching the
    # documented priority order.
    assert order_by.index("occurrence_count DESC") < order_by.index("created_at ASC") \
        < order_by.index("length(oc.name) ASC") < order_by.index("oc.name ASC")


# ── Empty-registry no-op (reasoned, not run) ─────────────────────────────────

def test_seed_is_reasoned_as_a_no_op_on_an_empty_registry():
    """No live DB is used here — this documents WHY the seed is a no-op on a
    fresh install, checked against the SQL's own structure, rather than
    proving it by running it (that needs `verify_schema_init.py`).

    `entity_vocab_seed_ranked` is built entirely FROM `entity_registry`
    (`registry_norm` selects `FROM entity_registry r` with no UNION/VALUES
    supplementing it), so zero rows in `entity_registry` means zero rows in
    `registry_norm`, zero in `occurrence_counts` (built FROM `registry_norm`),
    and zero in the ranked temp table. Both seed INSERTs SELECT FROM that temp
    table, so both affect zero rows: a fresh install's `entity_vocabulary` and
    `entity_vocab_aliases` are created but left empty, not specially handled.
    """
    sql = _sql()
    registry_norm = sql[sql.index("registry_norm AS ("):sql.index("occurrence_counts AS (")]
    assert "FROM entity_registry r" in registry_norm
    assert "UNION" not in registry_norm and "VALUES" not in registry_norm.upper()
