"""The fresh-install path must ship every object the running system depends on.

`schema_init.sql` is applied INSTEAD of the migration chain on a new deployment,
and nothing else reads it. So when it is incomplete the only person who finds
out is a stranger setting the framework up for the first time — and they have no
baseline to compare against. A guarantee that holds on every upgraded deployment
and on no new one is the worst shape a schema divergence can take.

These tests read the shipped ARTEFACTS rather than restating a list, which is
the same discipline the client-copy and constraint checks arrived at: a
hardcoded parity list goes stale invisibly, so derive the check from the thing
it is checking.

⚠ WHAT THESE DO **NOT** PROVE. They are string checks over a file. They cannot
tell whether the SQL parses, whether the trigger fires, or whether a fresh
database ends up equivalent to a live one. `migrations/verify_schema_init.py`
does that — it builds a throwaway database from `schema_init.sql` alone and
diffs the catalogues against the live schema. Run it after every migration; a
green suite here proves nothing about it.
"""
import os
import re

MIGRATIONS = os.path.join(os.path.dirname(__file__), "..", "shared-memory", "migrations")


def _schema_init() -> str:
    with open(os.path.join(MIGRATIONS, "schema_init.sql"), encoding="utf-8") as fh:
        return fh.read()


def _all_migration_sql() -> str:
    out = []
    for name in sorted(os.listdir(MIGRATIONS)):
        if name.endswith(".sql") and name != "schema_init.sql":
            with open(os.path.join(MIGRATIONS, name), encoding="utf-8") as fh:
                out.append(fh.read())
    return "\n".join(out)


# ── The save → consolidation wake-up signal ──────────────────────────────────
#
# The consolidation daemon LISTENs on `new_artifact`. For years nothing in this
# repository sent on that channel: the trigger existed only on the deployment
# the framework was developed on, created there by hand. Every other install ran
# a daemon waiting on a channel with no sender — not silent (a poll and a
# backstop still drive the cycle) but never prompted by an actual save.

def test_the_notify_channel_the_daemon_listens_on_has_a_sender():
    """Derived from the daemon, not restated beside it: whatever channel
    consolidation_loop LISTENs on must be sent to by shipped SQL."""
    loop_path = os.path.join(os.path.dirname(__file__), "..", "shared-memory",
                             "scripts", "consolidation_loop.py")
    with open(loop_path, encoding="utf-8") as fh:
        listened = set(re.findall(r"LISTEN\s+(\w+)\s*;", fh.read()))
    assert listened, "consolidation_loop no longer LISTENs — update this test deliberately"

    shipped = _schema_init() + _all_migration_sql()
    for channel in listened:
        assert f"pg_notify('{channel}'" in shipped, (
            f"the daemon LISTENs on '{channel}' but no shipped migration or "
            f"schema_init.sql ever sends on it — a fresh install would wait forever")


def test_schema_init_carries_the_notify_trigger_and_its_function():
    """The function alone is not enough; a trigger has to call it."""
    sql = _schema_init()
    assert "FUNCTION notify_new_artifact()" in sql
    assert "CREATE TRIGGER trg_notify_new_artifact" in sql
    assert "ON technical_docs" in sql


def test_the_notify_trigger_fires_on_insert_only():
    """AFTER INSERT, deliberately not AFTER UPDATE. The channel means 'a new
    artifact arrived'. Firing on UPDATE would make every metadata repair and
    backfill look like a fresh save and wake the cycle for work already done —
    and this framework runs one-time repairs over live data routinely."""
    sql = _schema_init()
    block = sql[sql.index("CREATE TRIGGER trg_notify_new_artifact"):]
    block = block[:block.index(";")]
    assert "AFTER INSERT" in block
    assert "UPDATE" not in block, "the notify trigger must not fire on UPDATE"


def test_every_function_in_schema_init_is_reachable_from_a_migration():
    """schema_init.sql is RENDERED by applying the migration chain to a scratch
    database, so anything in it must come from a migration. An object that
    exists only on one live machine cannot reach either install path — which is
    exactly how the notify trigger went missing for so long."""
    init_fns = set(re.findall(r"FUNCTION (?:public\.)?(\w+)\(", _schema_init()))
    chain = _all_migration_sql()
    for fn in init_fns:
        assert fn in chain, (
            f"{fn}() is in schema_init.sql but no migration creates it — it cannot "
            f"survive a regeneration, and a chain-based install will not have it")


# ── Objects a migration DROPPED must not reappear on a fresh install ─────────
#
# `schema_init.sql` is regenerated by applying the whole chain to a scratch
# database, so a DROP in a late migration is supposed to leave the object out of
# it. That is a claim about the generator, and the generator has silently got
# schema_init.sql wrong three times (CHECK, FOREIGN KEY, IDENTITY) — so it is
# checked rather than trusted. Getting it wrong here has a specific shape: a
# fresh install would come up carrying an object every upgraded install has
# deliberately removed, which is the divergence schema_init.sql exists to
# prevent, arriving from the other direction.

def test_a_dropped_object_is_absent_from_the_fresh_install():
    """Every object dropped by a migration, and never recreated by a later one,
    must be gone from `schema_init.sql`.

    Derived from the migration chain rather than restated beside it: the names
    come out of the `DROP INDEX` / `DROP TABLE` / `DROP SEQUENCE` statements
    themselves, so a future drop is covered the day it lands and cannot be
    forgotten here. (`DROP SEQUENCE` added at v0.9.72 — migration 040 uses it,
    and the first version of this parser silently skipped that whole form.)

    ⚠ KNOWN GAPS, LEFT DELIBERATELY AND WRITTEN DOWN RATHER THAN IMPLIED: the
    parser reads ONE object per statement, so a comma-separated
    `DROP INDEX a, b` would register only `a`; and it treats the whole chain as
    unordered when it un-drops a name, so a migration that CREATES an object an
    EARLIER one dropped clears the entry correctly while one that creates it in
    an earlier file and drops it in a later one is also cleared — wrongly. Both
    shapes are absent from this chain today. Widening the parser to cover them
    is worth doing the first time either appears, not before: a parser with
    cases nothing exercises is a parser nobody can prove.
    """
    chain_files = sorted(
        n for n in os.listdir(MIGRATIONS)
        if n.endswith(".sql") and n != "schema_init.sql"
    )
    dropped: dict[str, str] = {}
    for name in chain_files:
        with open(os.path.join(MIGRATIONS, name), encoding="utf-8") as fh:
            sql = fh.read()
        for obj in re.findall(
                r"DROP\s+(?:INDEX|TABLE|SEQUENCE)\s+(?:IF\s+EXISTS\s+)?"
                r"([A-Za-z_][\w.]*)",
                sql, re.I):
            dropped[obj.split(".")[-1]] = name
        # A later migration may legitimately recreate a name an earlier one
        # dropped — the drop is then not the last word about it.
        for obj in re.findall(
                r"CREATE\s+(?:UNIQUE\s+)?(?:INDEX|TABLE|SEQUENCE)\s+"
                r"(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z_][\w.]*)", sql, re.I):
            dropped.pop(obj.split(".")[-1], None)

    assert dropped, "no migration drops anything — this test has stopped covering it"
    init = _schema_init()
    for obj, migration in sorted(dropped.items()):
        assert not re.search(rf"\b{re.escape(obj)}\b", init), (
            f"{obj} is dropped by {migration} but still appears in "
            f"schema_init.sql — a fresh install would come up with an object "
            f"every upgraded install has removed")


def test_the_two_unusable_trigram_indexes_are_gone():
    """Migration 039, named explicitly as well as covered by the derived check
    above — because these two are the ones a future 'add an index for the
    proposal query' change would recreate by reflex. `gin_trgm_ops` cannot serve
    `similarity(name, $1) >= $2`; measured, both had an `idx_scan` of 0 against
    a `stats_reset` of NULL. ⚠ The `pg_trgm` EXTENSION must STAY — `similarity()`
    comes from it, and every proposal lookup calls it."""
    init = _schema_init()
    assert "idx_projects_name_trgm" not in init
    assert "idx_project_domains_name_trgm" not in init
    assert "CREATE EXTENSION IF NOT EXISTS pg_trgm;" in init


def test_the_retired_alias_ledger_is_gone_and_the_live_alias_table_stays():
    """Migration 040. ⛔ THE PAIR IS THE POINT: `alias_adjudications` (the
    ADR-017 verdict ledger, no writer since v0.8.60) leaves, and `aliases` — the
    live axis-alias identity table `project_aliases.alias_id` and
    `domain_aliases.alias_id` carry a FOREIGN KEY to — STAYS. Dropping the
    second because its name looks like the first would take the axis rename
    machinery with it."""
    init = _schema_init()
    assert "alias_adjudications" not in init
    assert "CREATE TABLE IF NOT EXISTS aliases (" in init
    assert "CREATE TABLE IF NOT EXISTS entity_embeddings (" in init
