-- Migration 027: projects.id is the identity and name stays a unique label, so
-- a rename is not a distributed rewrite and the fold gate cannot count one
-- project twice. technical_docs.metadata is left as what the client asserted.
-- This file cannot stamp Neo4j. reconcile_project_identity.py --apply does;
-- until then the insight gate fails closed instead of counting names.
-- project_aliases becomes id-only so a retired mapping stays true after a
-- rename. project_promotions keeps to_project as historical text beside
-- to_project_id, and drops the name FK so a ledger can remember a retired name.

-- BY DEFAULT, not ALWAYS: a restore must be able to carry ids across machines.
ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

-- SET NOT NULL after the backfill aborts the migration if any row did not resolve.
ALTER TABLE project_aliases    ADD COLUMN IF NOT EXISTS project_id    bigint;
ALTER TABLE project_promotions ADD COLUMN IF NOT EXISTS to_project_id bigint;

UPDATE project_aliases pa
   SET project_id = p.id
  FROM projects p
 WHERE p.name = pa.project
   AND pa.project_id IS NULL;

UPDATE project_promotions pr
   SET to_project_id = p.id
  FROM projects p
 WHERE p.name = pr.to_project
   AND pr.to_project_id IS NULL;

ALTER TABLE project_aliases    ALTER COLUMN project_id    SET NOT NULL;
ALTER TABLE project_promotions ALTER COLUMN to_project_id SET NOT NULL;

-- Both name foreign keys go before the primary key they depend on can be dropped.
ALTER TABLE project_aliases    DROP CONSTRAINT IF EXISTS project_aliases_project_fkey;
ALTER TABLE project_promotions DROP CONSTRAINT IF EXISTS project_promotions_to_project_fkey;

-- The name stays unique, so a lookup by the label a client types cannot be ambiguous.
ALTER TABLE projects DROP CONSTRAINT projects_pkey;
ALTER TABLE projects ADD CONSTRAINT projects_pkey PRIMARY KEY (id);
ALTER TABLE projects ADD CONSTRAINT projects_name_key UNIQUE (name);

ALTER TABLE project_aliases
    ADD CONSTRAINT project_aliases_project_id_fkey
    FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE project_promotions
    ADD CONSTRAINT project_promotions_to_project_id_fkey
    FOREIGN KEY (to_project_id) REFERENCES projects (id);

-- The alias's name column would be a second answer that goes stale on rename.
-- The promotions ledger keeps its text; there the text is the evidence.
ALTER TABLE project_aliases DROP COLUMN IF EXISTS project;

-- Resolution reads by alias string; the rename path filters by this pointer.
CREATE INDEX IF NOT EXISTS project_aliases_project_id_idx
    ON project_aliases (project_id);
