-- 027 — a project gets an IDENTITY, and the name goes back to being a label.
--
-- WHAT WAS WRONG. `projects.name` was the primary key, so the mutable string a
-- client happens to type was also the thing every other table pointed at and
-- every graph node was keyed on. That has three consequences, and the third is
-- the reason this migration is not cosmetic:
--
--   * A RENAME IS A DISTRIBUTED REWRITE. Records, a registry row, two foreign
--     keys, a graph node and every axis edge all carry the same string, so
--     moving it means rewriting all of them together and there is no stable
--     thing to map to while you do.
--   * AN ALIAS CANNOT MEAN WHAT IT SAYS. A row mapping an old spelling to a
--     current name is a mapping between two labels; if the target is renamed
--     the row is stale, so the alias layer needs re-pointing on every rename
--     and a retired row can outlive the truth it recorded.
--   * THE FOLD GATE USED A LABEL AS AN IDENTITY KEY. The insight gate requires
--     decisions from >= 2 distinct projects and counted `p.name`. That is
--     correct only while the node set happens to be one-to-one with the
--     registry, which nothing enforced: a partially-applied rename leaves two
--     nodes for one project, the same project counts twice, and a cross-project
--     insight is synthesised from a single project's decisions. The project axis
--     GATES CONSOLIDATION, so an identity error there is a synthesis error, not
--     a bookkeeping one.
--
-- WHAT THIS DOES. `projects.id` becomes the identity; `name` stays as a UNIQUE
-- label, still queryable, still what a human types and what a client asserts.
-- The two tables that referenced the name now reference the id.
--
-- WHY `technical_docs.metadata` IS NOT TOUCHED. A record's metadata records what
-- the client asserted at write time, and a creation-time assertion is history:
-- rewriting it to an id would destroy the only evidence of what the machine
-- actually claimed. The record reaches its identity through the registry, which
-- is exactly what an identity is for.
--
-- THE TWO REFERENCING TABLES ARE DELIBERATELY TREATED DIFFERENTLY:
--
--   * `project_aliases` is a POINTER, so it becomes id-only. An alias stops
--     being a mapping between two identities and becomes an alternate label ON
--     one identity — which is what makes an inactive row stay true forever
--     instead of needing maintenance every time its target is renamed.
--   * `project_promotions` is a LEDGER, so it keeps `to_project` as historical
--     TEXT and gains `to_project_id` as the durable pointer. The ledger's whole
--     purpose is to answer "what was this record moved onto, and when" — a
--     cascade or a rewrite would erase the name the promotion actually targeted.
--     Its foreign key on the name is DROPPED for the same reason: a ledger that
--     remembers a name must not be forced to forget it when that name stops
--     being current.
--
-- ⚠ THIS MIGRATION DOES NOT TOUCH NEO4J, and it cannot: Postgres migrations do
-- not reach the graph. The `:Project` nodes are stamped with `project_id` by
-- `scripts/reconcile_project_identity.py --apply`, which is idempotent and is
-- part of the documented upgrade path. Until it runs, nodes carry no identity
-- and the insight gate treats them as unidentified — it FAILS CLOSED, declining
-- to count them toward the two-project rule rather than falling back to the
-- name, because a name fallback would leave the defect live for the whole
-- upgrade window. `GET /health` reports the outstanding count so an incomplete
-- upgrade is visible rather than mysterious.

-- 1. The identity itself. GENERATED BY DEFAULT (not ALWAYS) so a restore or a
--    migration tool can carry ids across machines rather than having them
--    re-issued underneath the rows that point at them.
ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

-- 2. Both referencing tables gain their pointer and are backfilled through the
--    name they currently carry. The SET NOT NULL is the assertion, not a
--    formality: if any row failed to resolve, the migration fails here and the
--    transaction takes the whole thing back, rather than leaving a half-keyed
--    registry that later code would read as "this one has no identity".
ALTER TABLE project_aliases    ADD COLUMN IF NOT EXISTS project_id    bigint;
ALTER TABLE project_promotions ADD COLUMN IF NOT EXISTS to_project_id bigint;

UPDATE project_aliases pa
   SET project_id = p.id
  FROM projects p
 WHERE p.name = pa.project
   AND pa.project_id IS NULL;

UPDATE project_promotions pr
   SET to_project_id = p.id
  FROM projects p
 WHERE p.name = pr.to_project
   AND pr.to_project_id IS NULL;

ALTER TABLE project_aliases    ALTER COLUMN project_id    SET NOT NULL;
ALTER TABLE project_promotions ALTER COLUMN to_project_id SET NOT NULL;

-- 3. Release the name. Both foreign keys must go before the primary key they
--    depend on can be dropped.
ALTER TABLE project_aliases    DROP CONSTRAINT IF EXISTS project_aliases_project_fkey;
ALTER TABLE project_promotions DROP CONSTRAINT IF EXISTS project_promotions_to_project_fkey;

-- 4. The identity becomes the key; the name stays unique, so every lookup a
--    human or a client makes by name still works and still cannot be ambiguous.
ALTER TABLE projects DROP CONSTRAINT projects_pkey;
ALTER TABLE projects ADD CONSTRAINT projects_pkey PRIMARY KEY (id);
ALTER TABLE projects ADD CONSTRAINT projects_name_key UNIQUE (name);

-- 5. Re-point both tables at the identity.
ALTER TABLE project_aliases
    ADD CONSTRAINT project_aliases_project_id_fkey
    FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE project_promotions
    ADD CONSTRAINT project_promotions_to_project_id_fkey
    FOREIGN KEY (to_project_id) REFERENCES projects (id);

-- 6. The alias's name column goes. Keeping it would recreate the very drift
--    this migration removes: two answers to "which project does this alias
--    resolve to", one of which stops being true at the next rename. The ledger
--    keeps its text because there the text IS the evidence; here it is a stale
--    copy of a label the id already reaches.
ALTER TABLE project_aliases DROP COLUMN IF EXISTS project;

-- 7. Resolution reads by alias string and the rename path filters by target, so
--    the junction is indexed on the pointer as well as the string.
CREATE INDEX IF NOT EXISTS project_aliases_project_id_idx
    ON project_aliases (project_id);
