-- 028 — a domain becomes a REGISTERED, project-local section, with an identity.
--
-- WHAT A DOMAIN IS. A project is what a record belongs to; a domain is a SECTION
-- OF one project. `operations` under one project and `operations` under another
-- are two different sections that happen to share a word, so a domain is never
-- identified by its name alone — it is identified within its project.
--
-- WHAT WAS WRONG. `domain` was a free-text metadata field with nothing to be
-- unknown against. A typo and a new section were the same event, and both
-- entered the corpus silently. The field also drifted into meaning things it is
-- not: the commonest value on this corpus was the project's own name, which
-- carries no information the project does not already carry, and the second
-- commonest was a bucket word that names no section at all.
--
-- WHY THIS MIRRORS THE PROJECT REGISTRY RATHER THAN INVENTING A SHAPE. The
-- project axis already solved the same three problems — an unregistered value
-- must be LOUD, a rename must not be a distributed rewrite, and a retired
-- spelling must keep resolving — and it solved them with a registry keyed on a
-- surrogate id (027) plus an alias junction (024). Building the domain axis on
-- names would re-ship both defects that sequence removed, so:
--
--   * `project_domains.id` is the identity. `name` is a LABEL, unique WITHIN its
--     project, still queryable and still what an operator types.
--   * `project_domains.project_id` references `projects.id`, never the project
--     NAME — decision 1033. A domain of a renamed project must not need
--     re-pointing.
--   * `domain_aliases` lands HERE, with the table it references, in the shape
--     migration 024 fixed for both axes. It is not a follow-up: an axis whose
--     aliases arrive later spends the interval teaching callers that a retired
--     spelling is an unknown value.
--
-- ⛔ THIS MIGRATION CREATES SCHEMA AND NOTHING ELSE — no seed, no backfill, no
-- data repair. That is deliberate and it is not the plan being abandoned:
--
--   * A SEED WOULD HAVE TO NAME THINGS. Registering the sections this corpus
--     already uses means writing this deployment's project and section names
--     into a file that is published. Migration 022 seeded the project registry
--     by DERIVING it from the data precisely so that the file stayed portable
--     and named nothing; a domain seed cannot be derived the same way, because
--     the values needing registration are exactly the ones that must NOT be
--     registered verbatim.
--   * AN EMPTY REGISTRY IS THE CORRECT STATE FOR A NEW INSTALL. Domains arrive
--     through ingress, the same way projects do: an unregistered value is
--     refused with proposals, and the second submission registers it. There is
--     nothing a fresh deployment is missing here.
--   * THE OPERATOR-SIDE SEED AND DATA REPAIR ARE A ONE-TIME OPERATION run
--     against the deployment that needs them, recorded where one-time
--     operations are recorded. They are data, not schema.
--
-- ⚠ THIS MIGRATION DOES NOT TOUCH NEO4J, and it cannot. The `:Domain` nodes and
-- their `DOMAIN_OF` edges are written by the gateway's outbox worker at first
-- write, and the historical population is enqueued by
-- `scripts/backfill_domain_of.py`. `GET /health` reports `domain_identity` so an
-- incomplete deployment is visible rather than mysterious. The uniqueness
-- constraint on `Domain.domain_id` is declared in `neo4j_init.cypher` and
-- applied by `verify_neo4j_init.py --apply`, which is the one writer of graph
-- constraints.

-- 1. The registry. `id` is the identity, `name` is a label unique within the
--    project, and `description` is what makes a section legible to a stranger —
--    including a proposal engine, which matches on it as well as on the name.
CREATE TABLE IF NOT EXISTS project_domains (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  bigint      NOT NULL REFERENCES projects (id),
    name        text        NOT NULL,
    description text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    created_by  text        NOT NULL,

    -- A section is identified WITHIN its project, so the label is unique there
    -- and nowhere else. Two projects may both have an `operations` section and
    -- they are different sections.
    CONSTRAINT project_domains_name_unique UNIQUE (project_id, name),
    CONSTRAINT project_domains_not_blank CHECK (btrim(name) <> ''),

    -- The parked-project sentinel is reserved on this axis too. It is not a
    -- subject on either one, and a section named after it would be a section of
    -- nothing.
    CONSTRAINT project_domains_sentinel_reserved CHECK (name <> 'general_discussion'),

    -- Not a second key — the target of a COMPOSITE foreign key from
    -- `domain_aliases`, which is what lets that table carry `project_id`
    -- without it being able to disagree with this one. See the note there.
    CONSTRAINT project_domains_id_project UNIQUE (id, project_id)
);

-- Resolution reads by (project_id, name) — already covered by the unique
-- constraint's index — while proposals scan names across a project. The trigram
-- index is what makes a near miss produce usable proposals rather than a dead
-- end, exactly as it does for projects.
CREATE INDEX IF NOT EXISTS idx_project_domains_name_trgm
    ON project_domains USING gin (name gin_trgm_ops);

-- 2. The alias junction, in the shape migration 024 fixed. The alias STRING
--    lives in `aliases` and is shared by both axes; this table carries the
--    mapping and points at the domain IDENTITY, never at a name — the same
--    correction 027 made to `project_aliases`, applied here from the start
--    rather than as a later repair.
CREATE TABLE IF NOT EXISTS domain_aliases (
    id            bigserial   PRIMARY KEY,
    alias_id      bigint      NOT NULL REFERENCES aliases (id),
    domain_id     bigint      NOT NULL REFERENCES project_domains (id),
    -- The project the aliased domain belongs to. It is REACHABLE through
    -- `domain_id`, so carrying it here looks like the duplication this project
    -- spends its time removing — and it would be, were it not for the composite
    -- foreign key below. That key makes the pair (domain_id, project_id) valid
    -- only if it matches a real row of `project_domains`, so this column cannot
    -- become a second, disagreeing answer to "which project?"; it is the same
    -- answer, materialised where an index can use it.
    --
    -- ⚠ It is here because the A2 uniqueness rule below is PROJECT-LOCAL, and
    -- an index cannot follow a foreign key to find that out. The alternative —
    -- an expression index over a function that reads `project_domains` — would
    -- require declaring a table-reading function IMMUTABLE, which is false, and
    -- an index built on a false immutability claim is silently wrong rather
    -- than loudly broken.
    project_id    bigint      NOT NULL,
    -- A4 — mappings are SUPERSEDED, never deleted. The rename history is the
    -- ledger a later session reads instead of re-deriving the judgement.
    active        boolean     NOT NULL DEFAULT true,
    reason        text,
    created_by    text        NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    superseded_at timestamptz,

    CONSTRAINT domain_aliases_superseded_consistent
        CHECK ((active AND superseded_at IS NULL)
               OR (NOT active AND superseded_at IS NOT NULL)),

    CONSTRAINT domain_aliases_domain_project_fkey
        FOREIGN KEY (domain_id, project_id)
        REFERENCES project_domains (id, project_id)
);

-- A2, adapted to a project-local axis — at most one ACTIVE mapping per alias
-- PER PROJECT, enforced by the database rather than by discipline.
--
-- ⚠ THE PROJECT QUALIFIER IS THE WHOLE DIFFERENCE FROM `project_aliases`, and
-- dropping it would be the obvious mistake. A word that is a retired spelling of
-- one project's section is frequently a live section name — or a different
-- retired spelling — under another project. A globally unique active mapping
-- would make the first project to alias a common word own that word across the
-- entire deployment.
CREATE UNIQUE INDEX IF NOT EXISTS idx_domain_aliases_one_active
    ON domain_aliases (alias_id, project_id) WHERE active;

CREATE INDEX IF NOT EXISTS idx_domain_aliases_domain
    ON domain_aliases (domain_id);

-- A1 — THE ALIAS AND CANONICAL NAMESPACES ARE DISJOINT, WITHIN A PROJECT. A
-- string that is both a registered section of a project and an active alias for
-- a DIFFERENT section of that same project has two correct answers, and
-- resolution would pick by luck.
--
-- ⚠ SCOPED TO THE PROJECT, unlike the project-axis trigger, and for the reason
-- migration 024 already wrote down: the same spelling can legitimately be
-- canonical on one axis and an alias on another, or canonical in one project and
-- an alias in another. A global check here would refuse a legitimate
-- registration because some unrelated project retired that spelling once.
CREATE OR REPLACE FUNCTION assert_domain_alias_namespaces_disjoint()
RETURNS trigger AS $$
DECLARE
    v_alias text;
BEGIN
    IF TG_TABLE_NAME = 'domain_aliases' THEN
        IF NOT NEW.active THEN
            RETURN NEW;
        END IF;
        -- NEW.project_id, not a lookup through domain_id: the composite foreign
        -- key already guarantees the two agree, so re-deriving it here would
        -- only add a way for this rule and that key to disagree.
        SELECT name INTO v_alias FROM aliases WHERE id = NEW.alias_id;
        IF EXISTS (
            SELECT 1 FROM project_domains d
             WHERE d.project_id = NEW.project_id
               AND d.name = v_alias
        ) THEN
            RAISE EXCEPTION
                'alias % is also a registered domain of the same project — an '
                'alias and a canonical name must never be the same string within '
                'one project (A1)', v_alias;
        END IF;
    ELSE  -- project_domains
        IF EXISTS (
            SELECT 1 FROM domain_aliases da
              JOIN aliases a ON a.id = da.alias_id
              JOIN project_domains d ON d.id = da.domain_id
             WHERE da.active
               AND d.project_id = NEW.project_id
               AND a.name = NEW.name
        ) THEN
            RAISE EXCEPTION
                'domain % is already an active alias for another domain of this '
                'project — register the canonical name instead (A1)', NEW.name;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_domain_aliases_disjoint ON domain_aliases;
CREATE TRIGGER trg_domain_aliases_disjoint
    BEFORE INSERT OR UPDATE ON domain_aliases
    FOR EACH ROW EXECUTE FUNCTION assert_domain_alias_namespaces_disjoint();

DROP TRIGGER IF EXISTS trg_project_domains_disjoint ON project_domains;
CREATE TRIGGER trg_project_domains_disjoint
    BEFORE INSERT OR UPDATE ON project_domains
    FOR EACH ROW EXECUTE FUNCTION assert_domain_alias_namespaces_disjoint();
