-- Migration 028: a domain is a registered section of one project, keyed by id
-- the way projects are (027), with aliases in the 024 shape from the start.
-- project_id references projects.id, not the name (decision 1033), so a rename
-- does not re-point sections. No seed: unlike 022, the values that need
-- registering must not be copied verbatim into a published file, and an empty
-- registry is the right state for a new install. No Neo4j writes; the outbox
-- worker and backfill_domain_of.py own the graph.

CREATE TABLE IF NOT EXISTS project_domains (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  bigint      NOT NULL REFERENCES projects (id),
    name        text        NOT NULL,
    description text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    created_by  text        NOT NULL,

    -- Unique within the project only. Two projects may both have an operations section.
    CONSTRAINT project_domains_name_unique UNIQUE (project_id, name),
    CONSTRAINT project_domains_not_blank CHECK (btrim(name) <> ''),

    CONSTRAINT project_domains_sentinel_reserved CHECK (name <> 'general_discussion'),

    -- Not a second key. domain_aliases needs a composite FK target so its
    -- project_id cannot disagree with this row.
    CONSTRAINT project_domains_id_project UNIQUE (id, project_id)
);

-- Proposals scan names. Migration 039 drops this index: gin_trgm_ops cannot
-- answer similarity() compared to a literal floor.
CREATE INDEX IF NOT EXISTS idx_project_domains_name_trgm
    ON project_domains USING gin (name gin_trgm_ops);

-- Points at the domain id, not its name, so a rename does not re-point aliases.
CREATE TABLE IF NOT EXISTS domain_aliases (
    id            bigserial   PRIMARY KEY,
    alias_id      bigint      NOT NULL REFERENCES aliases (id),
    domain_id     bigint      NOT NULL REFERENCES project_domains (id),
    -- Denormalized so the one-active-alias index can be project-local. An
    -- expression index that read project_domains would need a false IMMUTABLE.
    -- The composite FK below keeps this column from disagreeing with domain_id.
    project_id    bigint      NOT NULL,
    -- Superseded, never deleted.
    active        boolean     NOT NULL DEFAULT true,
    reason        text,
    created_by    text        NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    superseded_at timestamptz,

    CONSTRAINT domain_aliases_superseded_consistent
        CHECK ((active AND superseded_at IS NULL)
               OR (NOT active AND superseded_at IS NOT NULL)),

    CONSTRAINT domain_aliases_domain_project_fkey
        FOREIGN KEY (domain_id, project_id)
        REFERENCES project_domains (id, project_id)
);

-- Per project, not global. A global unique would let the first project to
-- alias a common word own that word on every other project.
CREATE UNIQUE INDEX IF NOT EXISTS idx_domain_aliases_one_active
    ON domain_aliases (alias_id, project_id) WHERE active;

CREATE INDEX IF NOT EXISTS idx_domain_aliases_domain
    ON domain_aliases (domain_id);

-- Disjoint within one project only. The same spelling may be canonical in one
-- project and an alias in another; a global check would refuse that.
CREATE OR REPLACE FUNCTION assert_domain_alias_namespaces_disjoint()
RETURNS trigger AS $$
DECLARE
    v_alias text;
BEGIN
    IF TG_TABLE_NAME = 'domain_aliases' THEN
        IF NOT NEW.active THEN
            RETURN NEW;
        END IF;
        -- NEW.project_id, not a lookup: the composite FK already makes them agree.
        SELECT name INTO v_alias FROM aliases WHERE id = NEW.alias_id;
        IF EXISTS (
            SELECT 1 FROM project_domains d
             WHERE d.project_id = NEW.project_id
               AND d.name = v_alias
        ) THEN
            RAISE EXCEPTION
                'alias % is also a registered domain of the same project — an '
                'alias and a canonical name must never be the same string within '
                'one project (A1)', v_alias;
        END IF;
    ELSE  -- project_domains
        IF EXISTS (
            SELECT 1 FROM domain_aliases da
              JOIN aliases a ON a.id = da.alias_id
              JOIN project_domains d ON d.id = da.domain_id
             WHERE da.active
               AND d.project_id = NEW.project_id
               AND a.name = NEW.name
        ) THEN
            RAISE EXCEPTION
                'domain % is already an active alias for another domain of this '
                'project — register the canonical name instead (A1)', NEW.name;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_domain_aliases_disjoint ON domain_aliases;
CREATE TRIGGER trg_domain_aliases_disjoint
    BEFORE INSERT OR UPDATE ON domain_aliases
    FOR EACH ROW EXECUTE FUNCTION assert_domain_alias_namespaces_disjoint();

DROP TRIGGER IF EXISTS trg_project_domains_disjoint ON project_domains;
CREATE TRIGGER trg_project_domains_disjoint
    BEFORE INSERT OR UPDATE ON project_domains
    FOR EACH ROW EXECUTE FUNCTION assert_domain_alias_namespaces_disjoint();
