-- Migration 033: canonical entity spellings plus aliases, seeded from this
-- install's entity_registry and not consulted by the gateway yet. entity_registry
-- itself is not altered. decision:1380 — an alias is any asserted spelling, not
-- merely a case or punctuation variant, and a normalized value must still resolve
-- to only one identity. Names in RAISE EXCEPTION text are intentional
-- (decision:1380, finding F-10): they are operator-curated data inside the
-- trust boundary, not untrusted tenant input. A re-run is safe until an operator
-- has turned a seeded canonical into an alias of another entity; the trigger
-- then correctly refuses to recreate it as a canonical. Empty normalized keys
-- are filtered out of the seed and left in the registry.

BEGIN;

-- Lowercase, then strip non-alphanumerics. [:alnum:] is locale-dependent:
-- accented letters survive outside the C locale. IMMUTABLE because triggers
-- store the result; a later reader must call this function, not a copy.
CREATE OR REPLACE FUNCTION entity_normalize(raw_name text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT regexp_replace(lower(raw_name), '[^[:alnum:]]', '', 'g');
$$;

-- normalized_key is trigger-maintained, not GENERATED STORED: the schema
-- generator does not see a generation expression and would emit a bare column.
-- TEXT, not a length cap: the registry columns this seeds from are unbounded,
-- and a cap would abort the migration on a legal row.
CREATE TABLE IF NOT EXISTS entity_vocabulary (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT        NOT NULL,
    normalized_key TEXT        NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    registered_by  TEXT        NOT NULL DEFAULT 'system',

    CONSTRAINT entity_vocabulary_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT entity_vocabulary_normalized_key_not_empty CHECK (normalized_key <> ''),
    CONSTRAINT entity_vocabulary_normalized_key_unique UNIQUE (normalized_key)
);

CREATE INDEX IF NOT EXISTS idx_entity_vocabulary_created_at
    ON entity_vocabulary (created_at);

-- decision:1380 — uniqueness is the verbatim alias, not its normalized form.
-- Two spellings of one entity may share a key; the plain index is for lookup.
-- The FK points at the canonical id, never its name.
CREATE TABLE IF NOT EXISTS entity_vocab_aliases (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id        bigint      NOT NULL REFERENCES entity_vocabulary (id) ON DELETE CASCADE,
    alias            TEXT        NOT NULL,
    normalized_alias TEXT        NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by       TEXT        NOT NULL DEFAULT 'system',

    CONSTRAINT entity_vocab_aliases_not_blank CHECK (btrim(alias) <> ''),
    CONSTRAINT entity_vocab_aliases_normalized_alias_not_empty CHECK (normalized_alias <> ''),
    CONSTRAINT entity_vocab_aliases_alias_unique UNIQUE (alias)
);

CREATE INDEX IF NOT EXISTS idx_entity_vocab_aliases_entity_id
    ON entity_vocab_aliases (entity_id);
CREATE INDEX IF NOT EXISTS idx_entity_vocab_aliases_normalized_alias
    ON entity_vocab_aliases (normalized_alias);

-- decision:1380 — a UNIQUE constraint cannot see both tables. A canonical is
-- refused when an alias of a different identity already holds that key; the
-- same key falls through to ON CONFLICT. Compare normalized values, not row
-- ids: a BEFORE INSERT trigger runs after the new identity is assigned, so
-- no existing row can reference it yet.
-- decision:1380 — two concurrent transactions can both pass these BEFORE ROW
-- checks. Serializing vocabulary writes is left to the later ingress gate.
CREATE OR REPLACE FUNCTION entity_vocabulary_before_write()
RETURNS trigger AS $$
BEGIN
    NEW.normalized_key := entity_normalize(NEW.name);

    IF NEW.normalized_key = '' THEN
        RAISE EXCEPTION
            'entity "%" normalizes to the empty string — every character was '
            'stripped, so it cannot be registered as a canonical spelling',
            NEW.name;
    END IF;

    IF EXISTS (
        SELECT 1
          FROM entity_vocab_aliases a
          JOIN entity_vocabulary parent ON parent.id = a.entity_id
         WHERE a.normalized_alias = NEW.normalized_key
           AND parent.normalized_key <> NEW.normalized_key
    ) THEN
        RAISE EXCEPTION
            'entity "%" normalizes to "%", which is already registered as an '
            'alias resolving to a DIFFERENT identity — a normalized value '
            'must never resolve to two different identities',
            NEW.name, NEW.normalized_key;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_entity_vocabulary_before_write ON entity_vocabulary;
CREATE TRIGGER trg_entity_vocabulary_before_write
    BEFORE INSERT OR UPDATE ON entity_vocabulary
    FOR EACH ROW EXECUTE FUNCTION entity_vocabulary_before_write();

CREATE OR REPLACE FUNCTION entity_vocab_aliases_before_write()
RETURNS trigger AS $$
DECLARE
    v_parent_exists boolean;
BEGIN
    NEW.normalized_alias := entity_normalize(NEW.alias);

    IF NEW.normalized_alias = '' THEN
        RAISE EXCEPTION
            'alias "%" normalizes to the empty string — every character was '
            'stripped, so it cannot be registered', NEW.alias;
    END IF;

    SELECT EXISTS (SELECT 1 FROM entity_vocabulary WHERE id = NEW.entity_id)
      INTO v_parent_exists;
    IF NOT v_parent_exists THEN
        RAISE EXCEPTION
            'entity_vocab_aliases.entity_id % does not reference a known '
            'entity_vocabulary row', NEW.entity_id;
    END IF;

    -- A different canonical's key is a collision. The parent's own key is not.
    IF EXISTS (
        SELECT 1 FROM entity_vocabulary v
         WHERE v.normalized_key = NEW.normalized_alias
           AND v.id <> NEW.entity_id
    ) THEN
        RAISE EXCEPTION
            'alias "%" normalizes to "%", which is already a DIFFERENT '
            'canonical entity''s identity — a normalized value must never '
            'resolve to two different identities',
            NEW.alias, NEW.normalized_alias;
    END IF;

    -- other.id excludes this row's previous state on UPDATE. The ambiguity
    -- check is the entity_id comparison, not that id.
    IF EXISTS (
        SELECT 1 FROM entity_vocab_aliases other
         WHERE other.normalized_alias = NEW.normalized_alias
           AND other.entity_id <> NEW.entity_id
           AND other.id <> NEW.id
    ) THEN
        RAISE EXCEPTION
            'alias "%" normalizes to "%", which is already an alias of a '
            'DIFFERENT entity — a normalized value must never resolve to '
            'two different identities',
            NEW.alias, NEW.normalized_alias;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_entity_vocab_aliases_before_write ON entity_vocab_aliases;
CREATE TRIGGER trg_entity_vocab_aliases_before_write
    BEFORE INSERT OR UPDATE ON entity_vocab_aliases
    FOR EACH ROW EXECUTE FUNCTION entity_vocab_aliases_before_write();

-- Highest exact-string fact count, then earliest created_at, then shortest
-- name, then lexicographic name. An empty normalized key is skipped, not
-- deleted from entity_registry. A fresh install's empty registry seeds nothing.
CREATE TEMP TABLE entity_vocab_seed_ranked ON COMMIT DROP AS
WITH registry_norm AS (
    SELECT
        r.name,
        r.created_at,
        r.registered_by,
        entity_normalize(r.name) AS norm_key
    FROM entity_registry r
    WHERE entity_normalize(r.name) <> ''
),
occurrence_counts AS (
    SELECT
        rn.name,
        rn.norm_key,
        rn.created_at,
        rn.registered_by,
        (
            SELECT count(*)
              FROM technical_docs td
             WHERE (td.metadata->>'kind' IS NULL OR td.metadata->>'kind' = 'fact')
               AND td.metadata->'entities' IS NOT NULL
               AND jsonb_typeof(td.metadata->'entities') = 'array'
               AND td.metadata->'entities' ? rn.name
        ) AS occurrence_count
      FROM registry_norm rn
)
SELECT
    oc.name,
    oc.norm_key,
    oc.created_at,
    oc.registered_by,
    oc.occurrence_count,
    ROW_NUMBER() OVER (
        PARTITION BY oc.norm_key
        ORDER BY oc.occurrence_count DESC,
                 oc.created_at ASC,
                 length(oc.name) ASC,
                 oc.name ASC
    ) AS rnk
FROM occurrence_counts oc;

-- rnk = 1. registered_by is copied from the registry row, which is NOT NULL.
INSERT INTO entity_vocabulary (name, registered_by)
SELECT sr.name, sr.registered_by
  FROM entity_vocab_seed_ranked sr
 WHERE sr.rnk = 1
ON CONFLICT (normalized_key) DO NOTHING;

-- decision:1380 — ON CONFLICT targets the verbatim alias, not the normalized form.
INSERT INTO entity_vocab_aliases (entity_id, alias, created_by)
SELECT v.id, sr.name, sr.registered_by
  FROM entity_vocab_seed_ranked sr
  JOIN entity_vocabulary v ON v.normalized_key = sr.norm_key
 WHERE sr.rnk > 1
ON CONFLICT (alias) DO NOTHING;

COMMIT;
